import 'dart:async';

import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:intl/intl.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:rent_app/shared/shared.dart';
import 'package:rent_app/ui/widget/widget.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';
import '../../cubit/cubit.dart';
import '../../models/models.dart';

part 'spalsh_screen.dart';
part 'sign_in_page.dart';
part 'sign_up_page.dart';
part 'home_page.dart';
part 'main_page.dart';
part 'history_page.dart';
part 'get_started_page.dart';
part 'setting_page.dart';
part 'detail_car.dart';
part 'set_order_page.dart';
part 'payment_page.dart';
part 'payment_method.dart';
part 'detail_rent_car.dart';
part 'ilustration_page.dart';
part 'succes_order_page.dart';
